project_id = "tpwjhrurjiqefojvmrlj"

[functions.translate-message]
verify_jwt = false

[functions.train-avatar]
verify_jwt = false

[functions.chat-with-avatar]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.list-storage-files]
verify_jwt = false
